var config = {
    line: {
        "id"          : "id",
        "server_id"   : "varchar",
        "uid"         : "varchar",
        "account_type": "varchar",
        "channel"     : "varchar",
        "version"     : "varchar",
        "imei"        : "varchar",
        "login_time"  : "date",
        "ip"          : "varchar",
        "vip_level"   : "varchar",
        "iid"         : "varchar",
        "location"    : "varchar",
        "mobile_model": "varchar",
        "WIFI"        : "varchar",
        "sys_ver"     : "varchar",
        "nParam1"     : "varchar",
        "nParam2"     : "varchar",
        "nParam3"     : "varchar",
        "nParam4"     : "varchar",
        "sParam1"     : "varchar",
        "sParam2"     : "varchar",
        "sParam3"     : "varchar",
        "sParam4"     : "varchar",
        "sParam5"     : "varchar",
        "sParam6"     : "varchar",
        "session_id"  : "varchar",
        "ops_ver"     : "varchar",
        "pkg_display" : "varchar",
        "pkg_name"    : "varchar",
        "beans"       : "varchar",
        "caid"        : "varchar",
        "distinct_id" : "varchar",
        "tpfuid"      : "varchar",
        "unique_id"   : "varchar",
    },
}


module.exports = require('./init').init(config, __filename)