// 我们自己的
// 有日期后缀
var config = {
    line: {
        "iid"                 : "id",
        "date"                : "date",
        "server_id"           : "varchar",
        "id"                  : "varchar",
        "uid"                 : "varchar",
        "account_type"        : "varchar",
        "channel"             : "varchar",
        "version"             : "varchar",
        "imei"                : "varchar",
        "vip"                 : "varchar",
        "total_price"         : "varchar",
        "price"               : "varchar",
        "amount"              : "varchar",
        "goods_id"            : "varchar",
        "goods_name"          : "varchar",
        "notify_time"         : "date",
        "delive_time"         : "date",
        "scene"               : "varchar",
        "old_scene"           : "varchar",
        "sale_id"             : "varchar",
        "user_status"         : "varchar",
        "province"            : "varchar",
        "pay_type"            : "varchar",
        "isp"                 : "varchar",
        "room_id"             : "varchar",
        "subsidy_cnt"         : "varchar",
        "user_type_account"   : "varchar",
        "user_type_device"    : "varchar",
        "user_type_device_chn": "varchar",
        "pay_rule"            : "varchar",
        "user_source"         : "varchar",
        "pid"                 : "varchar",
        "before_adid"         : "varchar",
        "ad_id"               : "varchar",
        "sParam1"             : "varchar",
        "sParam2"             : "varchar",
        "sParam3"             : "varchar",
        "sParam4"             : "varchar",
        "sParam5"             : "varchar",
        "sParam6"             : "varchar",
        "iparam1"             : "varchar",
        "iparam2"             : "varchar",
        "iparam3"             : "varchar",
        "iparam4"             : "varchar",
        "iparam5"             : "varchar",
        "iparam6"             : "varchar",
        "need_sec_decode"     : "varchar",
    },
}


module.exports = require('./init').init(config, __filename)